### ISSUE TITLE
Add EntityFrameworkCore support

### ISSUE THREAD

**Issue by dbroudy** [dbroudy/LazyEntityGraph#11]
Add generator for `ModelMetadata` from EntityFrameworkCore's `DbContext`

- Create `LazyEntityGraph.EntityFrameworkCore`
- Add Tests `LazyEntityGraph.EntityFrameworkCore.Tests`

**Comment by ruskindantra** [comment]
Nice one @dbroudy, what are the prerequisites to start working on an issue in your repo?  I would be quite keen to get this working for you over time...

**Comment by dbroudy** [comment]
Thanks @ruskindantra! I started a branch on it, following the [EF6 to EF Core porting guide](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code) is pretty straightforward. The metadata API for EF Core is somewhat different (better) but not documented very well, so I'm just working through a couple things.  The biggest help will probably testing it out on your model once I have a pre-release version done, but I'll let you know if I get stuck on anything or run short on time.

**Comment by dbroudy** [comment]
@ruskindantra It took me a little while to get back around to this, but I just submitted a prerelease of 2.2.0 to nuget. Let me know if you run into any issues.
