### ISSUE TITLE
any way to intercept the automatic entity creation process ?

### ISSUE THREAD

**Issue by Pycnomerus** [dbroudy/LazyEntityGraph#13]
is there a way to intercept the creation graph for object in the tree ?

say we have 
```
public class A {
public virtual IEnumerable\<B\> someClass {get; set;}
}

public class B {
public string title { get; set; }
}
```

can we intercept the auto property for title upper in the graph ?

i would have with the` fixture.with()` operator but it doesn't support assignemnt has it's an expression tree.

**Comment by dbroudy** [comment]
It's really more of an AutoFixture question, LazyEntityGraph only really deals with setting up inverse relationships and keys for entities related by a model. 

If you're ok with configuring all instances of B, then you can just customize B, instead of trying to customize a.someClass[].title.
