### ISSUE TITLE
Navigating to property changes parent properties

### ISSUE THREAD

**Issue by iseesharp83** [dbroudy/LazyEntityGraph#14]
When accessing the navigation property of an entity that I've used AutoFixture to put into a test method, it changes non-navigation properties of the parent type that are related to the navigation property I accessed.

For example, if I had these two related entities, not related by convention but rather by attributes:

```
public class First
{
    [Key]
    public int FirstKey { get; set; }

    public int SecondKey { get; set; }

    public virtual Second Second { get; set; }

    public string SomeOtherProperty { get; set; }
}

public class Second
{
    [Key]
    public int SecondKey { get; set; }

    ... other stuff
}
```

Then passing these through the `ModelMetadataGenerator.LoadFromCoadFirstContext(...)` and customizing my fixture...

When I put it in a test, like so...

```
// Using NUnit 3 and NSubstitute
[Test]
[AutoNSubstituteData] //This is my custom class that adds the AutoFixture.NSubstitute customization
public void Test(First first)
{
    var firstKey = first.FirstKey; //Returns an auto-generated number, say 10
    var someOtherProperty = first.SomeOtherProperty; //Returns an auto-generated string, say "abc123"
    var firstKeysSecondKey = first.SecondKey; //Returns, say, 105

    var secondKey = first.Second.SecondKey; //Returns, say, 75
    var afterAccessingNavigation = first.FirstKey; //Now returns 75
    var anotherProperty = first.SomeOtherProperty; //Returns a different auto-generated string, say "123abc"
}
```

If that didn't make sense, basically when accessing navigation properties that have a relationship back to the accessing member, that member is _re-generated_ completely.

Of course, this keeps the "integrity" of the property constraints, which is probably desired in most cases.

However, I might expect `first.SecondKey` to _remain_ 105, and the `first.Second.SecondKey` to _also_ be generated as 105, and _SomeOtherProperty_ to not change from the original value.

Scouring through the metadata that `ModelMetadataGenerator` created, I found it made these contraints:

```
OneToManyPropertyConstraint<Second,First>
  PropInfo = ICollection<First>
  _inverse = Second
```

The _workaround_ is to access navigation properties up-front/immediately, as in make a `first.Second.SecondKey` call first, and then reference/use/expect/test against/etc the other variables as they will no longer change.

**Comment by dbroudy** [comment]
It makes sense, thanks for the detailed explanation. I believe what's happening is the initial key you're getting was generated by the fixture, then is overwritten when our constraints hooks in on the navigation property. I have a fix in mind, just copying the key in the other direction, since the navigation properties key can't have been accessed yet.

I'd be happy to look at a pull request if you have time, but it shouldn't take me too long to get this fixed otherwise.

**Comment by iseesharp83** [comment]
Hi! Awesome, thanks for the response. Unfortunately I've not got the additional time right now to create the solution and PR. For now I'm doing my work around by calling up-front the navigation properties that I'm expecting to use later.

**Comment by dbroudy** [comment]
@brazilianldsjaguar Sorry for the long delay. I added some unit tests to capture this behavior, but it's not occuring:

https://github.com/dbroudy/LazyEntityGraph/blob/5f462c04c6d4c0992b36fd4384ed9360e3575072/src/LazyEntityGraph.EntityFramework.Tests/EndToEndTests.cs#L44

I've seen it in the debugger, but it might just be some observer effect in the debugger accessing properties differently.

Would you mind checking out version 2.3.0 and see if this is still occurring?
