### ISSUE TITLE
Cannot add entity back to database

### ISSUE THREAD

**Issue by ClassyCircuit** [dbroudy/LazyEntityGraph#16]
Hi,
I would like to add the Autofixture generated entities back to the database, but I cannot do that because the created objects are of castle proxy type. EF does not recognize them.

I can't run these tests only in memory, I need to add the data to an actual database, so mocking is out of the question.
How can I do that ?

**Comment by ClassyCircuit** [comment]
@dbroudy could you please help me with this issue? Thanks

**Comment by dbroudy** [comment]
Hi @janissimsons,

That would have to be a change to AutoFixture itself, as it generates the proxy objects, but the idea behind LazyEntityGraph and AutoFixture is that you are mocking the database, so you probably need to look for another solution to generate your test data.

**Comment by ClassyCircuit** [comment]
@dbroudy could you suggest a way to convert these proxy objects back to EF entities? 
It would be nice if you could guide me in a general direction.

Basically what I am trying to accomplish is to generate test data for an object graph - and save it back to the database. (Taking into account foreign keys and other DB relationships). I haven't yet found a solution that would allow me to do this yet.
