### ISSUE TITLE
Exception when accessing collection property if it is defined in base class

### ISSUE THREAD

**Issue by azat-galiev** [dbroudy/LazyEntityGraph#17]
Hi! I get exception when adding generated entities to EF. Internally in AddAsync() method EF access one of my collection properties.

Brief description of my schema:
```
namespace A.B.C.Entities
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
    }

    public abstract class LocalizedEntity<T> : BaseEntity
        where T : Localization
    {
        public virtual ICollection<T> Localizations { get; set; }
    }

    public abstract class Localization : BaseEntity
    {
        public string LanguageCode { get; set; }
    }

    public class SomeEntity : LocalizedEntity<SomeEntityLocalized>
    {
        public string Name { get; set; }
    }

    public class SomeEntityLocalized : Localization
    {
        public string Name { get; set; }

        public virtual SomeEntity LocalizationFor { get; set; }
    }
}
```

And while adding some of related entities that have references to above ones, I get such exception:
```
System.InvalidCastException: Unable to cast object of type 'LazyEntityGraph.Core.Property`2[A.B.C.Entities.SomeEntityLocalized,A.B.C.Entities.SomeEntity]' to type 'LazyEntityGraph.Core.IProperty`2[A.B.C.Entities.SomeEntityLocalized,A.B.C.Entities.LocalizedEntity`1[A.B.C.Entities.SomeEntityLocalized]]'.
    at LazyEntityGraph.Core.VirtualPropertyInterceptor`1.Get[TProp](PropertyInfo propInfo)
```

**Comment by azat-galiev** [comment]
I've made PR to fix that issue: https://github.com/dbroudy/LazyEntityGraph/pull/18
Dear maintainers, review it please :)

**Comment by dbroudy** [comment]
@GaryFreeman Is there a way to reproduce this without involving adding to or saving a DbContext? The idea behind this library is to test without using a context, or to use a mock contest. If you were going to create an in memory context, like in your PR, you shouldn't need this library.

**Comment by azat-galiev** [comment]
Hmm, why it is bad to use InMemory context? With EF, it is really hard to mock the entire DbContext, so InMemory context seems like a pretty good solution.

**Comment by dbroudy** [comment]
I don't think there's anything wrong with using an in memory or other temporary context, though some unit test purists might disagree.

But it is a different approach, and the relationship mappings and caching of entities and IDs in the context is beyond the scope of what this library does.

As far as mocking db context, you're right, it's not trivial. I've been meaning to do a write up about my complete setup, but I also use https://github.com/scott-xu/EntityFramework.Testing and an interface for the DB context that only exposes the methods / properties I actually use so I don't have to mock as much.

**Comment by azat-galiev** [comment]
Ok, now it's clear to me, thanks! I think we can close the issue.
