### ISSUE TITLE
Need a .NET standard 2.1 port of LazyEntityGraph.EntityFramework package, please

### ISSUE THREAD

**Issue by GoalGator** [dbroudy/LazyEntityGraph#19]
Hello, we are using the LazyEntityGraph.EntityFramework package (.NET framework).
In about 5 weeks we are going to migrate our solution to .NET standard 2.1 and EF 6.4.

So, it would be great if you could provide .NET standard 2.1 support for the package.

P.S. You could cover both .NET standard 2.1 and .NET 4.5.2 via multi-target.

**Comment by dbroudy** [comment]
@GoalGator I'll be publishing a new version to NuGet shortly.
