### ISSUE TITLE
Any port to .net standard available or intended?

### ISSUE THREAD

**Issue by ruskindantra** [dbroudy/LazyEntityGraph#8]
Hi, I am just wondering if you were planning on porting this .net standard?

**Comment by dbroudy** [comment]
Yes, I do plan on porting this to .net standard.

**Comment by dbroudy** [comment]
@ruskindantra Thanks for the nudge on this, there's been a PR open that I wanted to take a look at for a while. There's a pre release version available on nuget.org now, and I will release an update shortly.

**Comment by ruskindantra** [comment]
Thanks @dbroudy! I don't see that package on nuget though...what will be the turnaround on that?

Also, I had a look at the changes and `LazyEntityGraph.EntityFramework` still has a reference to `EntityFramework` v6.1.3.  For .net standard they recommend `Microsoft.EntityFrameworkCore` which is currently at v2.0.3, therefore it's not fully compatible with .net standard I would have thought.

**Comment by dbroudy** [comment]
It's published in nuget, so maybe it takes a few hours, but you should see it soon if you don't already.

As far as EntityFramework, EF Core and EF6 are two different things. There are more details at https://docs.microsoft.com/en-us/ef including guidance on which one to use for your application, but LazyEntityGraph.EntityFramework will always support EF6, and therefore always target .NET Framework only.

I would like to add additional support for EF Core in a new project, very likely called LazyEntityGraph.EntityFrameworkCore. Now that the rest of the solution targets both .NET Standard and .NET Framework, I can start working (or accept a contribution) for EF Core support.

**Comment by ruskindantra** [comment]
Thanks @dbroudy, I look forward to `LazyEntityGraph.EntityFrameworkCore` :)

**Comment by dbroudy** [comment]
Added enhancement #11
